#[window]
[font]
size = 14.0
#
[font.normal]
family = "HackNerdFont"
style = "Regular"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.bold]
family = "HackNerdFont"
style="Bold"

[env]
TERM = "xterm-256color"

[general]
import = [
		"~/.config/alacritty/themes/catppuccin-mocha.toml"
]
